//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public long user_id { get; set; }
        public long role_id { get; set; }
        public long channel_id { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
