//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;

namespace MainService
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserRole = new HashSet<UserRole>();
        }
    
        public long user_id { get; set; }
        public string nickname { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<long> city_id { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<long> university_id { get; set; }
        public string group { get; set; }
        public string description { get; set; }
        public System.DateTime creation_time { get; set; }
    
        public virtual City City { get; set; }
        public virtual University University { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRole { get; set; }

    }
}
