//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultBase", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.Result))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.CrResultOfUserDtoGvCn2ESm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.CrResultOfChannelDtoGvCn2ESm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.CrResultOfEventDtoGvCn2ESm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfChannelRoleDtoGvCn2ESm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfUserDtoGvCn2ESm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfEventDtoGvCn2ESm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.DbRequestResultOfUserDtoGvCn2ESm))]
    public partial class ResultBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.ActionResult ActionResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.ActionResult ActionResult {
            get {
                return this.ActionResultField;
            }
            set {
                if ((this.ActionResultField.Equals(value) != true)) {
                    this.ActionResultField = value;
                    this.RaisePropertyChanged("ActionResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.CrResultOfUserDtoGvCn2ESm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.CrResultOfChannelDtoGvCn2ESm))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.CrResultOfEventDtoGvCn2ESm))]
    public partial class Result : ConsoleApplication1.ServiceReference1.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.Error[] ErrorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.Error[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrResultOfUserDtoGvCn2ESm", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class CrResultOfUserDtoGvCn2ESm : ConsoleApplication1.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.UserDto CreatedObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.UserDto CreatedObject {
            get {
                return this.CreatedObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedObjectField, value) != true)) {
                    this.CreatedObjectField = value;
                    this.RaisePropertyChanged("CreatedObject");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrResultOfChannelDtoGvCn2ESm", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class CrResultOfChannelDtoGvCn2ESm : ConsoleApplication1.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.ChannelDto CreatedObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.ChannelDto CreatedObject {
            get {
                return this.CreatedObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedObjectField, value) != true)) {
                    this.CreatedObjectField = value;
                    this.RaisePropertyChanged("CreatedObject");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrResultOfEventDtoGvCn2ESm", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class CrResultOfEventDtoGvCn2ESm : ConsoleApplication1.ServiceReference1.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.EventDto CreatedObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.EventDto CreatedObject {
            get {
                return this.CreatedObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedObjectField, value) != true)) {
                    this.CreatedObjectField = value;
                    this.RaisePropertyChanged("CreatedObject");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbRequestResultOfArrayOfChannelRoleDtoGvCn2ESm", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class DbRequestResultOfArrayOfChannelRoleDtoGvCn2ESm : ConsoleApplication1.ServiceReference1.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.ChannelRoleDto[] CreatedObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.ChannelRoleDto[] CreatedObject {
            get {
                return this.CreatedObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedObjectField, value) != true)) {
                    this.CreatedObjectField = value;
                    this.RaisePropertyChanged("CreatedObject");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbRequestResultOfArrayOfUserDtoGvCn2ESm", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class DbRequestResultOfArrayOfUserDtoGvCn2ESm : ConsoleApplication1.ServiceReference1.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.UserDto[] CreatedObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.UserDto[] CreatedObject {
            get {
                return this.CreatedObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedObjectField, value) != true)) {
                    this.CreatedObjectField = value;
                    this.RaisePropertyChanged("CreatedObject");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbRequestResultOfArrayOfEventDtoGvCn2ESm", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class DbRequestResultOfArrayOfEventDtoGvCn2ESm : ConsoleApplication1.ServiceReference1.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.EventDto[] CreatedObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.EventDto[] CreatedObject {
            get {
                return this.CreatedObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedObjectField, value) != true)) {
                    this.CreatedObjectField = value;
                    this.RaisePropertyChanged("CreatedObject");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbRequestResultOfUserDtoGvCn2ESm", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class DbRequestResultOfUserDtoGvCn2ESm : ConsoleApplication1.ServiceReference1.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.UserDto CreatedObjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.UserDto CreatedObject {
            get {
                return this.CreatedObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedObjectField, value) != true)) {
                    this.CreatedObjectField = value;
                    this.RaisePropertyChanged("CreatedObject");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionResult", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    public enum ActionResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PermissionDenied = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DatabaseError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncorrectParameter = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class UserDto : ConsoleApplication1.ServiceReference1.UserBaseDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication1.ServiceReference1.CheckStatus CheckStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApplication1.ServiceReference1.CheckStatus CheckStatus {
            get {
                return this.CheckStatusField;
            }
            set {
                if ((this.CheckStatusField.Equals(value) != true)) {
                    this.CheckStatusField = value;
                    this.RaisePropertyChanged("CheckStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Variable {
            get {
                return this.VariableField;
            }
            set {
                if ((object.ReferenceEquals(this.VariableField, value) != true)) {
                    this.VariableField = value;
                    this.RaisePropertyChanged("Variable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckStatus", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    public enum CheckStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArgumentIsNull = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LenghtIsIncorrect = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdDoesNotExist = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArgumentDoesNotMatchFormat = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArgumentIsNotUnique = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncorrectParametr = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserBaseDto", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.UserCrDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.UserDto))]
    public partial class UserBaseDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> UniversityIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Group {
            get {
                return this.GroupField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupField, value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> UniversityId {
            get {
                return this.UniversityIdField;
            }
            set {
                if ((this.UniversityIdField.Equals(value) != true)) {
                    this.UniversityIdField = value;
                    this.RaisePropertyChanged("UniversityId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserCrDto", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class UserCrDto : ConsoleApplication1.ServiceReference1.UserBaseDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelDto", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.ChannelRoleDto))]
    public partial class ChannelDto : ConsoleApplication1.ServiceReference1.ChannelCrDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ChannelIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ChannelId {
            get {
                return this.ChannelIdField;
            }
            set {
                if ((this.ChannelIdField.Equals(value) != true)) {
                    this.ChannelIdField = value;
                    this.RaisePropertyChanged("ChannelId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelCrDto", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.ChannelDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.ChannelRoleDto))]
    public partial class ChannelCrDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChannelRoleDto", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class ChannelRoleDto : ConsoleApplication1.ServiceReference1.ChannelDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventDto", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    public partial class EventDto : ConsoleApplication1.ServiceReference1.EventCrDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long EventIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long EventId {
            get {
                return this.EventIdField;
            }
            set {
                if ((this.EventIdField.Equals(value) != true)) {
                    this.EventIdField = value;
                    this.RaisePropertyChanged("EventId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventCrDto", Namespace="http://schemas.datacontract.org/2004/07/MainService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConsoleApplication1.ServiceReference1.EventDto))]
    public partial class EventCrDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ChannelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EventTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ImportanceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ChannelId {
            get {
                return this.ChannelIdField;
            }
            set {
                if ((this.ChannelIdField.Equals(value) != true)) {
                    this.ChannelIdField = value;
                    this.RaisePropertyChanged("ChannelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EventTime {
            get {
                return this.EventTimeField;
            }
            set {
                if ((this.EventTimeField.Equals(value) != true)) {
                    this.EventTimeField = value;
                    this.RaisePropertyChanged("EventTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ImportanceId {
            get {
                return this.ImportanceIdField;
            }
            set {
                if ((this.ImportanceIdField.Equals(value) != true)) {
                    this.ImportanceIdField = value;
                    this.RaisePropertyChanged("ImportanceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IScheduler")]
    public interface IScheduler {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetUserInformation", ReplyAction="http://tempuri.org/IScheduler/GetUserInformationResponse")]
        ConsoleApplication1.ServiceReference1.DbRequestResultOfUserDtoGvCn2ESm GetUserInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetUserInformation", ReplyAction="http://tempuri.org/IScheduler/GetUserInformationResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.DbRequestResultOfUserDtoGvCn2ESm> GetUserInformationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/EditUser", ReplyAction="http://tempuri.org/IScheduler/EditUserResponse")]
        ConsoleApplication1.ServiceReference1.CrResultOfUserDtoGvCn2ESm EditUser(ConsoleApplication1.ServiceReference1.UserCrDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/EditUser", ReplyAction="http://tempuri.org/IScheduler/EditUserResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CrResultOfUserDtoGvCn2ESm> EditUserAsync(ConsoleApplication1.ServiceReference1.UserCrDto user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/CreateChannel", ReplyAction="http://tempuri.org/IScheduler/CreateChannelResponse")]
        ConsoleApplication1.ServiceReference1.CrResultOfChannelDtoGvCn2ESm CreateChannel(ConsoleApplication1.ServiceReference1.ChannelDto channel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/CreateChannel", ReplyAction="http://tempuri.org/IScheduler/CreateChannelResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CrResultOfChannelDtoGvCn2ESm> CreateChannelAsync(ConsoleApplication1.ServiceReference1.ChannelDto channel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetChannels", ReplyAction="http://tempuri.org/IScheduler/GetChannelsResponse")]
        ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfChannelRoleDtoGvCn2ESm GetChannels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetChannels", ReplyAction="http://tempuri.org/IScheduler/GetChannelsResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfChannelRoleDtoGvCn2ESm> GetChannelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetChannelsUsers", ReplyAction="http://tempuri.org/IScheduler/GetChannelsUsersResponse")]
        ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfUserDtoGvCn2ESm GetChannelsUsers(long channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetChannelsUsers", ReplyAction="http://tempuri.org/IScheduler/GetChannelsUsersResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfUserDtoGvCn2ESm> GetChannelsUsersAsync(long channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/InviteUser", ReplyAction="http://tempuri.org/IScheduler/InviteUserResponse")]
        ConsoleApplication1.ServiceReference1.Result InviteUser(long userId, long channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/InviteUser", ReplyAction="http://tempuri.org/IScheduler/InviteUserResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Result> InviteUserAsync(long userId, long channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/AcceptInvite", ReplyAction="http://tempuri.org/IScheduler/AcceptInviteResponse")]
        ConsoleApplication1.ServiceReference1.ResultBase AcceptInvite(long channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/AcceptInvite", ReplyAction="http://tempuri.org/IScheduler/AcceptInviteResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ResultBase> AcceptInviteAsync(long channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/DeleteChannel", ReplyAction="http://tempuri.org/IScheduler/DeleteChannelResponse")]
        ConsoleApplication1.ServiceReference1.ResultBase DeleteChannel(long channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/DeleteChannel", ReplyAction="http://tempuri.org/IScheduler/DeleteChannelResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ResultBase> DeleteChannelAsync(long channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/DeleteUserFromChannel", ReplyAction="http://tempuri.org/IScheduler/DeleteUserFromChannelResponse")]
        ConsoleApplication1.ServiceReference1.ResultBase DeleteUserFromChannel(long channelId, long targetUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/DeleteUserFromChannel", ReplyAction="http://tempuri.org/IScheduler/DeleteUserFromChannelResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ResultBase> DeleteUserFromChannelAsync(long channelId, long targetUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/ChangeUsersRole", ReplyAction="http://tempuri.org/IScheduler/ChangeUsersRoleResponse")]
        ConsoleApplication1.ServiceReference1.Result ChangeUsersRole(long channelId, long targetUserId, long roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/ChangeUsersRole", ReplyAction="http://tempuri.org/IScheduler/ChangeUsersRoleResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Result> ChangeUsersRoleAsync(long channelId, long targetUserId, long roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/CreateEvent", ReplyAction="http://tempuri.org/IScheduler/CreateEventResponse")]
        ConsoleApplication1.ServiceReference1.CrResultOfEventDtoGvCn2ESm CreateEvent(ConsoleApplication1.ServiceReference1.EventCrDto ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/CreateEvent", ReplyAction="http://tempuri.org/IScheduler/CreateEventResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CrResultOfEventDtoGvCn2ESm> CreateEventAsync(ConsoleApplication1.ServiceReference1.EventCrDto ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/DeleteEvent", ReplyAction="http://tempuri.org/IScheduler/DeleteEventResponse")]
        ConsoleApplication1.ServiceReference1.Result DeleteEvent(long evId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/DeleteEvent", ReplyAction="http://tempuri.org/IScheduler/DeleteEventResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Result> DeleteEventAsync(long evId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/EditEvent", ReplyAction="http://tempuri.org/IScheduler/EditEventResponse")]
        ConsoleApplication1.ServiceReference1.CrResultOfEventDtoGvCn2ESm EditEvent(ConsoleApplication1.ServiceReference1.EventDto ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/EditEvent", ReplyAction="http://tempuri.org/IScheduler/EditEventResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CrResultOfEventDtoGvCn2ESm> EditEventAsync(ConsoleApplication1.ServiceReference1.EventDto ev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetEvents", ReplyAction="http://tempuri.org/IScheduler/GetEventsResponse")]
        ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfEventDtoGvCn2ESm GetEvents(int count, int offset, System.DateTime dateTime, long channelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetEvents", ReplyAction="http://tempuri.org/IScheduler/GetEventsResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfEventDtoGvCn2ESm> GetEventsAsync(int count, int offset, System.DateTime dateTime, long channelId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchedulerChannel : ConsoleApplication1.ServiceReference1.IScheduler, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchedulerClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IScheduler>, ConsoleApplication1.ServiceReference1.IScheduler {
        
        public SchedulerClient() {
        }
        
        public SchedulerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchedulerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1.ServiceReference1.DbRequestResultOfUserDtoGvCn2ESm GetUserInformation() {
            return base.Channel.GetUserInformation();
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.DbRequestResultOfUserDtoGvCn2ESm> GetUserInformationAsync() {
            return base.Channel.GetUserInformationAsync();
        }
        
        public ConsoleApplication1.ServiceReference1.CrResultOfUserDtoGvCn2ESm EditUser(ConsoleApplication1.ServiceReference1.UserCrDto user) {
            return base.Channel.EditUser(user);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CrResultOfUserDtoGvCn2ESm> EditUserAsync(ConsoleApplication1.ServiceReference1.UserCrDto user) {
            return base.Channel.EditUserAsync(user);
        }
        
        public ConsoleApplication1.ServiceReference1.CrResultOfChannelDtoGvCn2ESm CreateChannel(ConsoleApplication1.ServiceReference1.ChannelDto channel) {
            return base.Channel.CreateChannel(channel);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CrResultOfChannelDtoGvCn2ESm> CreateChannelAsync(ConsoleApplication1.ServiceReference1.ChannelDto channel) {
            return base.Channel.CreateChannelAsync(channel);
        }
        
        public ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfChannelRoleDtoGvCn2ESm GetChannels() {
            return base.Channel.GetChannels();
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfChannelRoleDtoGvCn2ESm> GetChannelsAsync() {
            return base.Channel.GetChannelsAsync();
        }
        
        public ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfUserDtoGvCn2ESm GetChannelsUsers(long channelId) {
            return base.Channel.GetChannelsUsers(channelId);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfUserDtoGvCn2ESm> GetChannelsUsersAsync(long channelId) {
            return base.Channel.GetChannelsUsersAsync(channelId);
        }
        
        public ConsoleApplication1.ServiceReference1.Result InviteUser(long userId, long channelId) {
            return base.Channel.InviteUser(userId, channelId);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Result> InviteUserAsync(long userId, long channelId) {
            return base.Channel.InviteUserAsync(userId, channelId);
        }
        
        public ConsoleApplication1.ServiceReference1.ResultBase AcceptInvite(long channelId) {
            return base.Channel.AcceptInvite(channelId);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ResultBase> AcceptInviteAsync(long channelId) {
            return base.Channel.AcceptInviteAsync(channelId);
        }
        
        public ConsoleApplication1.ServiceReference1.ResultBase DeleteChannel(long channelId) {
            return base.Channel.DeleteChannel(channelId);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ResultBase> DeleteChannelAsync(long channelId) {
            return base.Channel.DeleteChannelAsync(channelId);
        }
        
        public ConsoleApplication1.ServiceReference1.ResultBase DeleteUserFromChannel(long channelId, long targetUserId) {
            return base.Channel.DeleteUserFromChannel(channelId, targetUserId);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.ResultBase> DeleteUserFromChannelAsync(long channelId, long targetUserId) {
            return base.Channel.DeleteUserFromChannelAsync(channelId, targetUserId);
        }
        
        public ConsoleApplication1.ServiceReference1.Result ChangeUsersRole(long channelId, long targetUserId, long roleId) {
            return base.Channel.ChangeUsersRole(channelId, targetUserId, roleId);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Result> ChangeUsersRoleAsync(long channelId, long targetUserId, long roleId) {
            return base.Channel.ChangeUsersRoleAsync(channelId, targetUserId, roleId);
        }
        
        public ConsoleApplication1.ServiceReference1.CrResultOfEventDtoGvCn2ESm CreateEvent(ConsoleApplication1.ServiceReference1.EventCrDto ev) {
            return base.Channel.CreateEvent(ev);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CrResultOfEventDtoGvCn2ESm> CreateEventAsync(ConsoleApplication1.ServiceReference1.EventCrDto ev) {
            return base.Channel.CreateEventAsync(ev);
        }
        
        public ConsoleApplication1.ServiceReference1.Result DeleteEvent(long evId) {
            return base.Channel.DeleteEvent(evId);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.Result> DeleteEventAsync(long evId) {
            return base.Channel.DeleteEventAsync(evId);
        }
        
        public ConsoleApplication1.ServiceReference1.CrResultOfEventDtoGvCn2ESm EditEvent(ConsoleApplication1.ServiceReference1.EventDto ev) {
            return base.Channel.EditEvent(ev);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.CrResultOfEventDtoGvCn2ESm> EditEventAsync(ConsoleApplication1.ServiceReference1.EventDto ev) {
            return base.Channel.EditEventAsync(ev);
        }
        
        public ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfEventDtoGvCn2ESm GetEvents(int count, int offset, System.DateTime dateTime, long channelId) {
            return base.Channel.GetEvents(count, offset, dateTime, channelId);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.DbRequestResultOfArrayOfEventDtoGvCn2ESm> GetEventsAsync(int count, int offset, System.DateTime dateTime, long channelId) {
            return base.Channel.GetEventsAsync(count, offset, dateTime, channelId);
        }
    }
}
